extends:
  - '@commitlint/config-conventional'
plugins:
  - 'scope-empty-exceptions'
rules:
  header-max-length: [1, 'always', 80]
  scope-empty: [2, 'never', ['ci', 'chore']]
  type-enum:
    - 2
    - always
    - - ci
      - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - revert
      - chore
      - release
